spring:
  application:
    name: store
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=store_api;encrypt=false
    username: sa
    password: Ks120@120
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
